### ISSUE TITLE
Scene is brighter than it should

### ISSUE THREAD

**Issue by CMDR-JohnAlex** [ConstellationGamesOrg/Constellation-Engine-Archive01#76]
If you change the background colour to `0.2f, 0.3f, 0.3f, 1.0f` or if you load a model you can tell that the world is very.. bright?

For example, here is what the scene should look like with a model:
![image](https://user-images.githubusercontent.com/94056103/180624873-95db1b26-68c2-4ea0-99d6-59238c7d4dc2.png)

Yet this is what it actually looks like with the same background colour and model:
![image](https://user-images.githubusercontent.com/94056103/180624880-5e291392-69e4-4965-a653-14d1bdce436b.png)

We need to test if this is an issue on Linux and Mac builds.

**Comment by Piras314** [comment]
@CMDR-JohnAlex reproduces on linux
